name: Britizen Quiz Application
version: 1.0.5
slug: britizen-quiz
description: Life in the UK practice tests with progress tracking
url: https://github.com/chanchurbansal/lit-uk
codeowners:
  - '@chanchurbansal'
startup: application
boot: auto
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
ports:
  3000/tcp: 3000
map:
  - data
environment:
  NODE_ENV: production
init: false


